AWSTemplateFormatVersion: 2010-09-09
Description: "DynamoDB"
 
Parameters:
  Env:
    Type: String
    AllowedValues: [dev, test, prod]
    Description: Environment name
 

Resources:
  User:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub "${Env}-UsersTable"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      Tags:
        - Key: Env
          Value: !Ref Env

Outputs:
  UsersTableName:
    Value: !Ref User
    Export:
      Name: !Sub "${Env}-UsersTableName"
 
  UsersTableArn:
    Value: !GetAtt User.Arn
    Export:
      Name: !Sub "${Env}-UsersTableArn"