AWSTemplateFormatVersion: "2010-09-09"
Description: ECR Repository Stack

Parameters:
  Env:
    Type: String
    AllowedValues: [dev, test, prod]
    Description: Environment name
    
Resources:
  MyEcrRepository:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName: !Sub "${Env}-user-management-repo"
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last 30 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 30
                },
                "action": { "type": "expire" }
              }
            ]
          }
      Tags:
        - Key: Env
          Value: !Ref Env
 
Outputs:
  EcrRepositoryName:
    Value: !Ref MyEcrRepository
    Export:
      Name: !Sub "${Env}-EcrRepoName"